### ISSUE TITLE
Missing chs files

### ISSUE THREAD

**Issue by amigalemming** [Rufflewind/blas-hs#6]
The Haskell files state that they are generated from Chs files like `src/Blas/Primitive/Unsafe_.chs`. I cannot find such a file in the Hackage package or in the github repository.

**Comment by Rufflewind** [comment]
They are [generated from the `Makefile`](https://github.com/Rufflewind/blas-hs/blob/f8e90b26bc9865618802dce9ccf21fc2b5c032be/Makefile#L84-L89).
