### ISSUE TITLE
Add to stackage?

### ISSUE THREAD

**Issue by tmcdonell** [Rufflewind/blas-hs#7]
Would you be interested in adding this package to stackage? Since it is stable I doubt you'd have to do any maintenance after getting it added. Instructions for adding packages are [here](https://github.com/fpco/stackage/blob/master/MAINTAINERS.md#adding-a-package).

**Comment by Rufflewind** [comment]
Sent a PR → https://github.com/fpco/stackage/pull/2805

**Comment by Rufflewind** [comment]
https://github.com/fpco/stackage/pull/2805 has been merged.

**Comment by tmcdonell** [comment]
Thanks! (:
