### ISSUE TITLE
Incorrect call of `fail` on a Monad in tests

### ISSUE THREAD

**Issue by svmhdvn** [Rufflewind/blas-hs#8]
Seen when building on nixos:

```
tests/TestUtils.hs:37:3: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
   |
37 |   fail msg     = do
   |
```

Should be easy to change to a MonadFail constraint, but I am not able to test it right now.

**Comment by Rufflewind** [comment]
Thanks for the reporting this! Should be fixed now.
